Repository joakime/experiments-with-release-drafter, pull requests merged in 2020-10, with the labels that each got.

#12 test touch
  README.md
Labels: bug

#13 test touch README jetty-11
  README.md
Labels: bug

#14 test touch README jetty-10
  README.md
Labels: bug

#15 test release-drafter olamy branch jetty-9.4.x
  .github/workflows/release-drafter-10.0.x.yml
  .github/workflows/release-drafter-11.0.x.yml
  .github/workflows/release-drafter-9.4.x.yml
Labels: feature

#16 test release-drafter olamy branch jetty-10.0.x
  .github/workflows/release-drafter-10.0.x.yml
  .github/workflows/release-drafter-11.0.x.yml
  .github/workflows/release-drafter-9.4.x.yml
Labels: feature

#17 Adding zee.txt to 9 branch.
  zee.txt
Labels: enhancement

#18 test foo 9.4.x
  README.md
Labels: feature

#19 something important jetty-12.0.x
  README.md
Labels: feature

#20 3 foo
  README.md
Labels: enhancement

#21 only one foo
  README.md
Labels: bug
